### ISSUE TITLE
Current Net Worth; stuck on Fetching Data

### ISSUE THREAD

**Issue by Slipperyjim8** [viktorgullmark/exile-party#11]
Equipment tab works, Currency Tab shows Net Worth stuck on fetching data,
https://i.imgur.com/KCSWwv3.png
Area's tab also doesn't work.
Log file seemed to validate.

**Comment by viktorgullmark** [comment]
Have you tried starting the app as administrator? We noticed some people have issues reading the Client.txt if not started in admin-mode.

Let me know how it works out, otherwhise we'll look into this further.

**Comment by Megaddd** [comment]
The program takes about 2-3 minutes to update net worth for me as well, and I just have a lot of div cards and a bunch of maps and only 6 stash tabs, but Jim has dozens of stash tabs filled with ridiculous amounts of stuff, you should see one of his videos: https://youtu.be/DIMvoTsnBxQ?t=198

I'd imagine his stash would take like 20-30 minutes to update if the time scales linearly.

**Comment by petterannerwall** [comment]
We do have a limit to retrive at most 20 stashtabs, even if you have more selected in the settings. This is poorly communicated and we should probably add a description for that in the settings view. 

it could probably some time but i would very surprised to see times larger then 2 minutes for parsing even 20 stashtabs. But as of now its impossible to see when a snapshot start and finish in the interface.

**Comment by Slipperyjim8** [comment]
For reference I've only ever selected one tab in my stash, it still never updates, I've restarted, ran as admin and let it sit there for an hour, I'll try re-installing :>

**Comment by Megaddd** [comment]
@Slipperyjim8 I've noticed it updates when you switch zones, where sitting in my hideout indefinitely it will not.

**Comment by Slipperyjim8** [comment]
Welp, now it works and I seem like an idiot :>
No idea what I did differently, or even is reinstalling is what fixed it.

**Comment by petterannerwall** [comment]
Hah @Slipperyjim8  it happen's i'm just happy that it works for you! For the record the networth graph don't trigger a snapshot if you don't change area. It's currently bound to that event to lessen the spam on poe.ninja and ggg's api when you idle in hideout and go AFK.
