### ISSUE TITLE
Time in Area is a bit off

### ISSUE THREAD

**Issue by xxjokeronexx** [viktorgullmark/exile-party#16]
![image](https://user-images.githubusercontent.com/14196113/42423518-e5783ee6-82fb-11e8-9a7d-18532ee101f4.png)

Something is off with the time calculation here. The timestamp is correct, but it obviously didn't took 40 minutes for completion. The average time in that area doesn't seem to be influenced by the 40 minutes though.

**Comment by viktorgullmark** [comment]
Hmm, I think we missed to include a file in our latest publish. I'll publish a hotfix for this within a few minutes that should solve this. What happened is that several maps seem to be "merged" into one timing.

Let me know if the upcoming release(0.4.5) doesn't solve this.

**Comment by viktorgullmark** [comment]
Tested locally and should work as of 0.4.5, if it's still an issue re-open the issue.
