### ISSUE TITLE
Unbind keybinds

### ISSUE THREAD

**Issue by aggixx** [viktorgullmark/exile-party#19]
There doesn't seem to be any way to unbind keybinds. Also these keybinds seem to intercept those keypresses globally, even when PoE isn't in focus, which means if a keybind is set to Shift C then its impossible to type a capital letter C anywhere... Rather annoying. Ended up having manually edit the settings file so that I can use the program at all right now.

**Comment by viktorgullmark** [comment]
Hey, thanks for the issue. We've had several reports on this and most of it is already sorted out locally, but not released yet. We've changed the default-binds and will go ahead and add an option to disable them entirely.

Will keep this issue open until the release has been published.

**Comment by aggixx** [comment]
Good news, thanks.

**Comment by viktorgullmark** [comment]
0.5.1 is now live with these changes, see the changelog for more information.

Closing this issue.
