### ISSUE TITLE
Keybinds cannot be disabled.

### ISSUE THREAD

**Issue by Megaddd** [viktorgullmark/exile-party#22]
Suggest adding a checkbox to 'disable' keybinds, disabling their functionality and greying their options out in settings.

Current 'workaround' is setting to hard-to-use key combinations such as alt-P and alt-O.

**Comment by viktorgullmark** [comment]
This will be added in 0.5.1

**Comment by viktorgullmark** [comment]
0.5.1 is now live, closing this
