### ISSUE TITLE
Disconnections and no reconnecting?

### ISSUE THREAD

**Issue by vegeto079** [viktorgullmark/exile-party#26]
I've been getting this approx. every couple hours:

> Could not connect to ExileParty server

I have to restart the program every time it happens, which leads me to two things:
-How come it does not try to auto-reconnect (or is it trying and failing)?
-When the program turns on I have to re-do the initial setup every time. Can it just auto-remember instead and have a spot to 'forget' in the program if I want to make changes?

**Comment by EThaNol2005** [comment]
Can confirm this Problem. A reconnect function will be nice.
Me and my mates, need so restart the program quite often.

**Comment by viktorgullmark** [comment]
Closing this, as we added reconnect-functionality in the last release. Improvements to this functionality will be added in the next version as well.
