### ISSUE TITLE
[UI Bug] Abyssal Sockets / Socketed Jewels doesn't show

### ISSUE THREAD

**Issue by EsCanavi** [viktorgullmark/exile-party#6]
Abyssal socket / Socketed Eye Jewel doesn't show (Yet the mouse over works)

Slot tested
- Abyssal Belt
- Abyssal Glove
- Abyssal Boots
- Inventory

Seen in those tab 
- Current Group
- Inspect Player

1 Abyssal socket item has the "mouse over" pop-up a bit off range (also demonstrated in pic)

(Edit 1:  https://i.imgur.com/hATPzcB.png )
(Edit 2:  added more info on 1 Abyssal Item)

**Comment by viktorgullmark** [comment]
This will be fixed in the next release, will  close when released.

**Comment by viktorgullmark** [comment]
Closing this, released with 0.4.1
