### ISSUE TITLE
Doubled up currency count after death.

### ISSUE THREAD

**Issue by Megaddd** [viktorgullmark/exile-party#7]
My entire stash showed up as gains twice in a row in quick succession.
https://imgur.com/a/Xo7ovLP

**Comment by Megaddd** [comment]
relevant client.txt part - https://pastebin.com/Y0jfHr6z
Graph updating very infrequently (once every 3-5 maps), showing incorrect chaos values when it does.

I did not gain 150c between second-last and last nodes.
The last graph node is doubled up on nearly the same time.
https://gfycat.com/TiredAmpleKentrosaurus

**Comment by viktorgullmark** [comment]
We're looking into this issue. We've had several people reporting the same. Will post an status-update here when we have a fix ready.

**Comment by viktorgullmark** [comment]
A fix for this should now be live in 0.4.3. If you still experience this let us know!
